export type { SalonSearchResult, SearchFilters } from '../../api/types'
export { searchSalons, getFeaturedSalons } from './basic'
export { searchSalonsWithFuzzyMatch, getNearbyServices } from './advanced'
export { getSalonSearchSuggestions } from './suggestions'
export { getPopularCities, getAvailableStates } from './filters'
