export { AdminDashboardPage } from './admin-dashboard'
export { AdminOverviewAppointmentsTab } from './admin-overview-appointments-tab'
export { AdminOverviewMessagesTab } from './admin-overview-messages-tab'
export { AdminOverviewRevenueTab } from './admin-overview-revenue-tab'
export { AdminOverviewReviewsTab } from './admin-overview-reviews-tab'
export { AdminOverviewStaffTab } from './admin-overview-staff-tab'
export { AdminOverviewTabs } from './admin-overview-tabs'
export { DashboardError } from './dashboard-error'
export { DashboardHeader } from './dashboard-header'
export { DashboardHero } from './dashboard-hero'
export { PlatformMetrics } from './platform-metrics'
export { PlatformMetricCard } from './platform-metric-card'
export { getPlatformMetricsConfig } from './platform-metrics-config'
export { RecentSalons } from './recent-salons'
export { UserRoleStats } from './user-role-stats'

// Re-export utilities
export * from './admin-overview-utils'
