import 'server-only'

export * as inventoryAlertsQueries from '@/features/business/inventory-alerts/api/queries'
export * as inventoryCategoryQueries from '@/features/business/inventory-categories/api/queries'
export * as inventoryLocationQueries from '@/features/business/inventory-locations/api/queries'
export * as inventoryMovementQueries from '@/features/business/inventory-movements/api/queries'
export * as inventoryOrderQueries from '@/features/business/inventory-purchase-orders/api/queries'
export * as inventoryProductQueries from '@/features/business/inventory-products/api/queries'
export * as inventoryStockLevelQueries from '@/features/business/inventory-stock-levels/api/queries'
export * as inventorySupplierQueries from '@/features/business/inventory-suppliers/api/queries'
export * as inventoryUsageQueries from '@/features/business/inventory-usage/api/queries'
