export type { StructuredDataProps } from './structured-data/schema-types'
export { StructuredData } from './structured-data/component'
export { generateOrganizationSchema } from './structured-data/organization-schema'
export { generateWebSiteSchema } from './structured-data/website-schema'
export { generateBreadcrumbSchema } from './structured-data/breadcrumb-schema'
export { generateFAQSchema } from './structured-data/faq-schema'
export { generateLocalBusinessSchema, type SalonSchemaInput } from './structured-data/local-business-schema'
export { generateServiceSchema, type ServiceSchemaInput } from './structured-data/service-schema'
export { generateReviewSchema, type ReviewSchemaInput } from './structured-data/review-schema'
