import 'server-only'

export { getPlatformAnalyticsSnapshot } from './internal/queries/platform'
export { getAllAppointments } from './internal/queries/appointments'
export { getAllSalons } from './internal/queries/salons'
export { getAllUsers } from './internal/queries/users'
export { getAllReviews } from './internal/queries/reviews'
export { getAllStaff } from './internal/queries/staff'
export { getInventoryOverview } from './internal/queries/inventory'
export { getRevenueOverview } from './internal/queries/revenue'
export { getMessagesOverview } from './internal/queries/messages'
