import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Shield, Activity, AlertTriangle, UserX } from 'lucide-react'
import { getSecurityOverview, getAuditLogs, getSecurityEvents } from '@/features/admin/security/api/queries'
import { AuditLogsTable } from './audit-logs-table'
import { SecurityEventsTable } from './security-events-table'
import { requireAnyRole, ROLE_GROUPS } from '@/lib/auth'

export async function AdminSecurityClient() {
  await requireAnyRole(ROLE_GROUPS.PLATFORM_ADMINS)

  const dateFrom = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  const dateTo = new Date().toISOString()

  const [overview, auditLogs, securityEvents] = await Promise.all([
    getSecurityOverview(dateFrom, dateTo),
    getAuditLogs({ limit: 50 }),
    getSecurityEvents({ limit: 50 }),
  ])

  return (
    <section className="py-16 md:py-24 lg:py-32">
      <div className="mx-auto w-full max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col gap-10">
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <CardTitle>Total Audit Logs</CardTitle>
                  <Activity className="h-4 w-4 text-muted-foreground" />
                </div>
                <CardDescription>Captured actions over the last 7 days.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-semibold">{overview.totalAuditLogs}</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <CardTitle>Security Events</CardTitle>
                  <Shield className="h-4 w-4 text-secondary" />
                </div>
                <CardDescription>Alerts generated by automated monitoring.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-semibold">{overview.totalSecurityEvents}</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <CardTitle>Failed Logins</CardTitle>
                  <UserX className="h-4 w-4 text-accent" />
                </div>
                <CardDescription>Attempts rejected during the past week.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-semibold">{overview.failedLogins}</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <CardTitle>Suspicious Activity</CardTitle>
                  <AlertTriangle className="h-4 w-4 text-destructive" />
                </div>
                <CardDescription>Flagged sessions requiring follow-up.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-semibold">{overview.suspiciousActivity}</p>
              </CardContent>
            </Card>
          </div>

          <div>
            <p className="text-sm font-semibold">Recent Security Events</p>
            <p className="text-sm text-muted-foreground mb-4">
              Failed login attempts and suspicious activity
            </p>
            <SecurityEventsTable events={securityEvents} />
          </div>

          <div>
            <p className="text-sm font-semibold">Recent Audit Logs</p>
            <p className="text-sm text-muted-foreground mb-4">All user actions and system events</p>
            <AuditLogsTable logs={auditLogs} />
          </div>
        </div>
      </div>
    </section>
  )
}
