import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Shield, Activity, AlertTriangle, UserX } from 'lucide-react'
import { getSecurityOverview, getAuditLogs, getSecurityEvents } from '@/features/admin/security/api/queries'
import { AuditLogsTable } from './audit-logs-table'
import { SecurityEventsTable } from './security-events-table'
import { requireAnyRole, ROLE_GROUPS } from '@/lib/auth'
import { Item, ItemActions, ItemContent, ItemGroup, ItemHeader, ItemMedia } from '@/components/ui/item'
import { AdminSection } from '@/features/admin/common/components'

export async function AdminSecurityClient(): Promise<React.JSX.Element> {
  await requireAnyRole(ROLE_GROUPS.PLATFORM_ADMINS)

  const dateFrom = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  const dateTo = new Date().toISOString()

  const [overview, auditLogs, securityEvents] = await Promise.all([
    getSecurityOverview(dateFrom, dateTo),
    getAuditLogs({ limit: 50 }),
    getSecurityEvents({ limit: 50 }),
  ])

  return (
    <AdminSection>
      <div className="flex flex-col gap-10">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card>
            <CardHeader>
              <ItemGroup>
                <Item variant="muted">
                  <ItemHeader>
                    <ItemContent>
                      <CardTitle>Total Audit Logs</CardTitle>
                      <CardDescription>Captured actions over the last 7 days.</CardDescription>
                    </ItemContent>
                    <ItemActions>
                      <Activity className="size-4 text-muted-foreground" />
                    </ItemActions>
                  </ItemHeader>
                </Item>
              </ItemGroup>
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-semibold">{overview.totalAuditLogs}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <ItemGroup>
                <Item variant="muted">
                  <ItemHeader>
                    <ItemContent>
                      <CardTitle>Security Events</CardTitle>
                      <CardDescription>Alerts generated by automated monitoring.</CardDescription>
                    </ItemContent>
                    <ItemActions>
                      <Shield className="size-4 text-secondary" />
                    </ItemActions>
                  </ItemHeader>
                </Item>
              </ItemGroup>
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-semibold">{overview.totalSecurityEvents}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <ItemGroup>
                <Item variant="muted">
                  <ItemHeader>
                    <ItemContent>
                      <CardTitle>Failed Logins</CardTitle>
                      <CardDescription>Attempts rejected during the past week.</CardDescription>
                    </ItemContent>
                    <ItemActions>
                      <UserX className="size-4 text-accent" />
                    </ItemActions>
                  </ItemHeader>
                </Item>
              </ItemGroup>
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-semibold">{overview.failedLogins}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <ItemGroup>
                <Item variant="muted">
                  <ItemHeader>
                    <ItemContent>
                      <CardTitle>Suspicious Activity</CardTitle>
                      <CardDescription>Flagged sessions requiring follow-up.</CardDescription>
                    </ItemContent>
                    <ItemActions>
                      <AlertTriangle className="size-4 text-destructive" />
                    </ItemActions>
                  </ItemHeader>
                </Item>
              </ItemGroup>
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-semibold">{overview.suspiciousActivity}</p>
            </CardContent>
          </Card>
        </div>

        <div>
          <p className="text-sm font-semibold">Recent Security Events</p>
          <p className="mb-4 text-sm text-muted-foreground">
            Failed login attempts and suspicious activity
          </p>
          <SecurityEventsTable events={securityEvents} />
        </div>

        <div>
          <p className="text-sm font-semibold">Recent Audit Logs</p>
          <p className="mb-4 text-sm text-muted-foreground">All user actions and system events</p>
          <AuditLogsTable logs={auditLogs} />
        </div>
      </div>
    </AdminSection>
  )
}
