'use client'

import { useEffect, useMemo, useState } from 'react'

import { Badge } from '@/components/ui/badge'
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableFooter,
  TableRow,
} from '@/components/ui/table'
import { formatDistanceToNow } from 'date-fns'
import { Shield, AlertTriangle, AlertCircle } from 'lucide-react'
import type { SecurityEvent } from '@/features/admin/security/api/queries'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from '@/components/ui/empty'
import { Item, ItemContent, ItemGroup, ItemMedia } from '@/components/ui/item'
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from '@/components/ui/pagination'

interface SecurityEventsTableProps {
  events: SecurityEvent[]
}

export function SecurityEventsTable({ events }: SecurityEventsTableProps): React.JSX.Element {
  if (events.length === 0) {
    return (
      <Empty>
        <EmptyMedia variant="icon">
          <Shield />
        </EmptyMedia>
        <EmptyHeader>
          <EmptyTitle>No security events found</EmptyTitle>
          <EmptyDescription>Security insights populate when suspicious or anomalous activity is detected.</EmptyDescription>
        </EmptyHeader>
        <EmptyContent>Monitoring runs continuously and will surface events automatically.</EmptyContent>
      </Empty>
    )
  }

  const getSeverityBadge = (severity: string) => {
    const level = severity.toLowerCase()
    const formatted = level.replace(/\b\w/g, (char) => char.toUpperCase())
    if (level === 'critical') {
      return (
        <div className="flex items-center gap-1">
          <AlertCircle className="size-3" />
          <Badge variant="destructive">{formatted}</Badge>
        </div>
      )
    }
    if (level === 'high') {
      return (
        <div className="flex items-center gap-1">
          <AlertTriangle className="size-3" />
          <Badge variant="destructive">{formatted}</Badge>
        </div>
      )
    }
    if (level === 'medium') {
      return <Badge variant="secondary">{formatted}</Badge>
    }
    return <Badge variant="outline">{formatted}</Badge>
  }

  const [page, setPage] = useState(1)
  const pageSize = 10

  const pageCount = Math.max(1, Math.ceil(events.length / pageSize))

  const paginatedEvents = useMemo(() => {
    const start = (page - 1) * pageSize
    return events.slice(start, start + pageSize)
  }, [events, page, pageSize])

  useEffect(() => {
    setPage((current) => Math.min(current, pageCount))
  }, [pageCount])

  const startIndex = (page - 1) * pageSize + 1
  const endIndex = Math.min(page * pageSize, events.length)

  return (
    <Card>
      <CardHeader>
        <div className="sr-only">
          <ItemGroup>
            <Item>
              <ItemContent>
                <ItemTitle>Security events</ItemTitle>
              </ItemContent>
              <ItemContent>
                <ItemDescription>Recent platform security activity</ItemDescription>
              </ItemContent>
            </Item>
          </ItemGroup>
        </div>
      </CardHeader>
      <CardContent>
        <ScrollArea className="w-full">
          <Table>
            <TableCaption>Recent security events and alerts generated by monitoring.</TableCaption>
            <TableHeader>
              <TableRow>
                <TableHead>Event Type</TableHead>
                <TableHead>Severity</TableHead>
                <TableHead>User</TableHead>
                <TableHead>IP Address</TableHead>
                <TableHead>Time</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {paginatedEvents.map((event) => (
                <TableRow key={event.id}>
                  <TableCell>
                    <ItemGroup>
                      <Item variant="muted">
                        <ItemMedia variant="icon">
                          <Shield className="size-4 text-muted-foreground" />
                        </ItemMedia>
                        <ItemContent>
                          <span className="font-medium">{event.event_type}</span>
                        </ItemContent>
                      </Item>
                    </ItemGroup>
                  </TableCell>
                  <TableCell>{getSeverityBadge(event.severity)}</TableCell>
                  <TableCell>
                    <span className="text-sm">
                      {event.user_email || event.user_id || 'Unknown'}
                    </span>
                  </TableCell>
                  <TableCell>
                    <span className="font-mono text-sm text-muted-foreground">
                      {event.ip_address || 'Unknown'}
                    </span>
                  </TableCell>
                  <TableCell>
                    <span className="text-sm text-muted-foreground">
                      {formatDistanceToNow(new Date(event.created_at), { addSuffix: true })}
                    </span>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
            <TableFooter>
              <TableRow>
                <TableCell colSpan={4}>
                  Showing {startIndex}-{endIndex} of {events.length} events
                </TableCell>
                <TableCell className="text-right">
                  Page {page} of {pageCount}
                </TableCell>
              </TableRow>
            </TableFooter>
          </Table>
          <ScrollBar orientation="horizontal" />
        </ScrollArea>
        <Pagination className="mt-4">
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious
                href="#"
                onClick={(event) => {
                  event.preventDefault()
                  if (page > 1) {
                    setPage(page - 1)
                  }
                }}
                className={page === 1 ? 'pointer-events-none opacity-50' : undefined}
              />
            </PaginationItem>
            {Array.from({ length: pageCount }, (_, index) => {
              const value = index + 1
              return (
                <PaginationItem key={value}>
                  <PaginationLink
                    href="#"
                    isActive={value === page}
                    onClick={(event) => {
                      event.preventDefault()
                      setPage(value)
                    }}
                  >
                    {value}
                  </PaginationLink>
                </PaginationItem>
              )
            })}
            <PaginationItem>
              <PaginationNext
                href="#"
                onClick={(event) => {
                  event.preventDefault()
                  if (page < pageCount) {
                    setPage(page + 1)
                  }
                }}
                className={page === pageCount ? 'pointer-events-none opacity-50' : undefined}
              />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </CardContent>
    </Card>
  )
}
