export { useDescriptionForm } from '../../hooks/use-description-form'
export type { ArrayFieldState, DescriptionFieldState } from '../../hooks/use-description-form'
export { DescriptionsSection } from './descriptions-section'
export { SeoSection } from './seo-section'
export { ArrayFieldsSection } from './array-fields-section'
export * from './array-input'
export * from './highlights-section'
export * from './keywords-section'
export * from './recognition-section'
