import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

import type { StaffRevenueBreakdown } from '@/features/staff/analytics/api/queries'
import { formatCurrency } from './utils'

interface RevenueTabProps {
  revenueBreakdown: StaffRevenueBreakdown[]
}

export function RevenueTab({ revenueBreakdown }: RevenueTabProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Service Revenue Breakdown</CardTitle>
        <CardDescription>Revenue generated by each service</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {revenueBreakdown.length > 0 ? (
            revenueBreakdown.map((service) => (
              <div
                key={service.service_id}
                className="flex items-center justify-between border-b pb-3 last:border-0 last:pb-0"
              >
                <div className="space-y-1">
                  <span className="text-sm font-medium leading-tight text-foreground">
                    {service.service_name}
                  </span>
                  <span className="block text-sm text-muted-foreground">
                    {service.bookings_count} bookings • {formatCurrency(service.avg_price)} avg
                  </span>
                </div>
                <div className="text-right">
                  <span className="text-sm font-semibold leading-tight text-foreground">
                    {formatCurrency(service.total_revenue)}
                  </span>
                </div>
              </div>
            ))
          ) : (
            <div className="py-4 text-center">
              <CardDescription>No revenue data available for this period</CardDescription>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}
