import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty'

import type { StaffRevenueBreakdown } from '@/features/staff/analytics/api/queries'
import { formatCurrency } from './utils'

interface RevenueTabProps {
  revenueBreakdown: StaffRevenueBreakdown[]
}

export function RevenueTab({ revenueBreakdown }: RevenueTabProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Service Revenue Breakdown</CardTitle>
        <CardDescription>Revenue generated by each service</CardDescription>
      </CardHeader>
      <CardContent>
        {revenueBreakdown.length > 0 ? (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Service</TableHead>
                <TableHead className="text-right">Bookings</TableHead>
                <TableHead className="text-right">Avg Price</TableHead>
                <TableHead className="text-right">Total Revenue</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {revenueBreakdown.map((service) => (
                <TableRow key={service.service_id}>
                  <TableCell className="font-medium">{service.service_name}</TableCell>
                  <TableCell className="text-right">{service.bookings_count}</TableCell>
                  <TableCell className="text-right">{formatCurrency(service.avg_price)}</TableCell>
                  <TableCell className="text-right font-semibold">
                    {formatCurrency(service.total_revenue)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <Empty>
            <EmptyHeader>
              <EmptyTitle>No revenue data available</EmptyTitle>
              <EmptyDescription>Adjust the reporting range to see service performance.</EmptyDescription>
            </EmptyHeader>
          </Empty>
        )}
      </CardContent>
    </Card>
  )
}
