'use client'

import { Fragment } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemGroup,
  ItemSeparator,
  ItemTitle,
} from '@/components/ui/item'
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty'
import type { StaffRevenueBreakdown } from '@/features/staff/analytics/api/queries'

interface RevenueBreakdownTabProps {
  revenueBreakdown: StaffRevenueBreakdown[]
}

export function RevenueBreakdownTab({ revenueBreakdown }: RevenueBreakdownTabProps) {
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount)
  }

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Service Revenue Breakdown</CardTitle>
          <CardDescription>Revenue generated by each service</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {revenueBreakdown.length > 0 ? (
              <ItemGroup className="gap-0">
                {revenueBreakdown.map((service, index) => (
                  <Fragment key={service.service_id}>
                    <Item variant="outline" size="sm">
                      <ItemContent>
                        <ItemTitle>{service.service_name}</ItemTitle>
                        <ItemDescription>
                          {service.bookings_count} bookings • {formatCurrency(service.avg_price)} avg
                        </ItemDescription>
                      </ItemContent>
                      <ItemActions>
                        <div className="text-right text-sm font-semibold leading-tight">
                          {formatCurrency(service.total_revenue)}
                        </div>
                      </ItemActions>
                    </Item>
                    {index < revenueBreakdown.length - 1 ? <ItemSeparator /> : null}
                  </Fragment>
                ))}
              </ItemGroup>
            ) : (
              <Empty>
                <EmptyHeader>
                  <EmptyTitle>No revenue data available</EmptyTitle>
                  <EmptyDescription>Select a different period to see revenue performance.</EmptyDescription>
                </EmptyHeader>
              </Empty>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
