export { ProfitabilitySection } from './profitability-section'
export { ServiceOverviewSection } from './service-overview-section'
export { StaffPerformanceSection } from './staff-performance-section'
export { ServicePairingsSection } from './service-pairings-section'
export { DurationAccuracySection } from './duration-accuracy-section'
