-- Supabase advisor remediation (FK covering indexes) captured on 2025-11-16
BEGIN;

CREATE INDEX IF NOT EXISTS analytics_events_updated_by_id_fkey_idx ON analytics.analytics_events (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_daily_metrics_profiles_created_by_id_idx ON analytics.daily_metrics (created_by_id);
CREATE INDEX IF NOT EXISTS fk_daily_metrics_profiles_updated_by_id_idx ON analytics.daily_metrics (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_manual_transactions_profiles_updated_by_id_idx ON analytics.manual_transactions (updated_by_id);
CREATE INDEX IF NOT EXISTS mv_refresh_log_created_by_id_fkey_idx ON analytics.mv_refresh_log (created_by_id);
CREATE INDEX IF NOT EXISTS mv_refresh_log_updated_by_id_fkey_idx ON analytics.mv_refresh_log (updated_by_id);
CREATE INDEX IF NOT EXISTS archive_audit_log_performed_by_fkey_idx ON archive.archive_audit_log (performed_by);
CREATE INDEX IF NOT EXISTS fk_message_threads_profiles_created_by_id_idx ON communication.message_threads (created_by_id);
CREATE INDEX IF NOT EXISTS fk_message_threads_profiles_updated_by_id_idx ON communication.message_threads (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_webhook_queue_profiles_created_by_id_idx ON communication.webhook_queue (created_by_id);
CREATE INDEX IF NOT EXISTS fk_webhook_queue_profiles_updated_by_id_idx ON communication.webhook_queue (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_customer_favorites_profiles_created_by_id_idx ON engagement.customer_favorites (created_by_id);
CREATE INDEX IF NOT EXISTS fk_customer_favorites_profiles_updated_by_id_idx ON engagement.customer_favorites (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_review_helpful_votes_profiles_created_by_id_idx ON engagement.review_helpful_votes (created_by_id);
CREATE INDEX IF NOT EXISTS fk_review_helpful_votes_profiles_updated_by_id_idx ON engagement.review_helpful_votes (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_reviews_customer_id_idx ON engagement.salon_reviews (customer_id);
CREATE INDEX IF NOT EXISTS fk_salon_reviews_profiles_created_by_id_idx ON engagement.salon_reviews (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_reviews_profiles_updated_by_id_idx ON engagement.salon_reviews (updated_by_id);
CREATE INDEX IF NOT EXISTS audit_logs_updated_by_id_fkey_idx ON identity.audit_logs (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_profiles_metadata_profiles_created_by_id_idx ON identity.profiles_metadata (created_by_id);
CREATE INDEX IF NOT EXISTS fk_profiles_metadata_profiles_updated_by_id_idx ON identity.profiles_metadata (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_profiles_preferences_profiles_created_by_id_idx ON identity.profiles_preferences (created_by_id);
CREATE INDEX IF NOT EXISTS fk_profiles_preferences_profiles_updated_by_id_idx ON identity.profiles_preferences (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_user_roles_salon_id_idx ON identity.user_roles (salon_id);
CREATE INDEX IF NOT EXISTS fk_amenities_users_created_by_id_idx ON organization.amenities (created_by_id);
CREATE INDEX IF NOT EXISTS fk_amenities_users_updated_by_id_idx ON organization.amenities (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_languages_users_created_by_id_idx ON organization.languages (created_by_id);
CREATE INDEX IF NOT EXISTS fk_languages_users_updated_by_id_idx ON organization.languages (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_payment_methods_users_created_by_id_idx ON organization.payment_methods (created_by_id);
CREATE INDEX IF NOT EXISTS fk_payment_methods_users_updated_by_id_idx ON organization.payment_methods (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_amenities_users_created_by_id_idx ON organization.salon_amenities (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_amenities_users_updated_by_id_idx ON organization.salon_amenities (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_languages_users_created_by_id_idx ON organization.salon_languages (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_languages_users_updated_by_id_idx ON organization.salon_languages (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_media_users_created_by_id_idx ON organization.salon_media (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_media_users_updated_by_id_idx ON organization.salon_media (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_metrics_users_created_by_id_idx ON organization.salon_metrics (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_metrics_users_updated_by_id_idx ON organization.salon_metrics (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_payment_methods_users_created_by_id_idx ON organization.salon_payment_methods (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_payment_methods_users_updated_by_id_idx ON organization.salon_payment_methods (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_settings_users_created_by_id_idx ON organization.salon_settings (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_settings_users_updated_by_id_idx ON organization.salon_settings (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_specialties_users_created_by_id_idx ON organization.salon_specialties (created_by_id);
CREATE INDEX IF NOT EXISTS fk_salon_specialties_users_updated_by_id_idx ON organization.salon_specialties (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_salons_owner_id_idx ON organization.salons (owner_id);
CREATE INDEX IF NOT EXISTS fk_specialties_users_created_by_id_idx ON organization.specialties (created_by_id);
CREATE INDEX IF NOT EXISTS fk_specialties_users_updated_by_id_idx ON organization.specialties (updated_by_id);
CREATE INDEX IF NOT EXISTS fk_staff_profiles_user_id_idx ON organization.staff_profiles (user_id);
CREATE INDEX IF NOT EXISTS auditable_entity_created_by_id_fkey_idx ON patterns.auditable_entity (created_by_id);
CREATE INDEX IF NOT EXISTS auditable_entity_deleted_by_id_fkey_idx ON patterns.auditable_entity (deleted_by_id);
CREATE INDEX IF NOT EXISTS auditable_entity_updated_by_id_fkey_idx ON patterns.auditable_entity (updated_by_id);
CREATE INDEX IF NOT EXISTS soft_deletable_deleted_by_id_fkey_idx ON patterns.soft_deletable (deleted_by_id);

COMMIT;
